version: '3'
services:
  web:
    image: brettt89/silverstripe-web
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8080:80
    links:
      - db
    environment:
       - DOCUMENT_ROOT=/var/www
       - SS_TRUSTED_PROXY_IPS=*
       - SS_ENVIRONMENT_TYPE=dev
       - SS_DATABASE_SERVER=db
       - SS_DATABASE_NAME=development
       - SS_DATABASE_USERNAME=test
       - SS_DATABASE_PASSWORD=test
       - SS_DEFAULT_ADMIN_USERNAME=admin
       - SS_DEFAULT_ADMIN_PASSWORD=password

  db:
    image: mysql:5.7
    volumes:
      - mysqldb:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=development
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

volumes:
  mysqldb: